apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: q7ycu6dqr-java-quarkus
  janus-idp.io/tekton: q7ycu6dqr-java-quarkus
  backstage.io/kubernetes-id: q7ycu6dqr-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: q7ycu6dqr-java-quarkus
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
